# Generated by Django 3.2.4 on 2021-07-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='date_created',
            field=models.DateField(default='07/09/21'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateField(default='07/09/21'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='date_created',
            field=models.DateField(default='07/09/21'),
        ),
    ]
