# Generated by Django 3.2.4 on 2021-07-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210709_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
