# Generated by Django 3.2.4 on 2021-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210711_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
