# Generated by Django 3.2.4 on 2021-07-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listings_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
