# Generated by Django 3.2.4 on 2021-07-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='listing',
            new_name='listings',
        ),
    ]
