# Generated by Django 3.2.4 on 2021-07-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_listing_watch_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
